config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users, controllers: { confirmations: 'confirmations' }
  # a route that maps the URL "/users/:author_id/posts"
  # to the "index" action of the "posts" controller.
   # It a Nested route to access posts for a specific user
  get "/users/:author_id/posts", to: "posts#index", as: :user_posts
 # a route that maps the URL "/posts/:id" to the "show"
 # action of the "posts" controller.
  get "/posts/:id", to: "posts#show", as: :user_post
  # a route that maps the URL "/users" to the "index" action
  # of the "users" controller. This means that when a user
  # visits the "/users" URL, the "index" action in the
  #"users" controller will be executed.
  root "users#index"
  # a route that maps the URL "/users/:id" to the "show"
  # action of the "users" controller.
  get "/users/:id", to: "users#show", as: :user

  # a route that maps the URL "/posts" to the "create" action of the "posts"
  # controller. This means that when a user submits a POST request to the "/posts"
  # URL, the "create" action in the "posts" controller will be executed.
  post "/posts", to: "posts#create"

 # a route that maps the URL "/posts/:id/comments" to the "create_comment"
 # action of the "posts" controller.
  post "/posts/:id/comments", to: "comments#create_comment", as: :post_comments

 # a route that maps the URL "/posts/:id/likes" to the "create_like"
 # action of the "posts" controller.
  post "/posts/:id/likes", to: "likes#create_like", as: :post_likes

  # route that maps the URL "/users/:author_id/posts" to the "create" action of the "posts"
  # controller.
  post "/users/:author_id/posts", to: "posts#create", as: :create_user_post
  delete "/posts/:id", to: "posts#destroy", as: :delete_post
  delete "/comments/:id", to: "comments#destroy", as: :delete_comment

  namespace :api do
    resources :users, only: [] do
       resources :posts, only: [:index] do
        resources :comments, only: [:index, :create]
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  # Include default devise modules. Others available are
  has_many :comments, foreign_key: 'author_id'
  # counter_cache makes sure Rails automatically update the PostCounter
  # attribute in the User model when posts are created or destroyed.
  has_many :posts, foreign_key: 'author_id', counter_cache: true
  has_many :likes, foreign_key: 'author_id'

  # The code `validates :Name, presence: true` is validating that the `Name`
  # attribute of the `User` model is present, meaning it cannot be blank or nil.
  validates :name, presence: true
  # is adding a validation to the `User` model. It ensures that the `PostCounter` attribute is a
  # numerical value and that it is greater than or equal to 0. This means that the `PostCounter`
  # attribute cannot be a non-integer value or a negative number.
  # validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # The function retrieves the three most recent posts written
  # by the author.
  def three_most_recent_posts
    Post.where(author_id: id).order(created_at: :desc).limit(3)
  end

  def admin?
    role == 'admin'
  end
end

# Code to verify if the three_most_recent_posts method is working

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # The index function retrieves all users from the database.
  def index
    @users = User.all
  end

  def edit
    current_user.update(user_params)
  end

  # The function retrieves a user object from the database
  # based on the provided ID.
  def show
    @user = User.find(params[:id])
    @posts = Post.includes(:user).where(author_id: @user.id)
    cookies[:user_id] = @user.id
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def image_url(user)
    user.photo || "https://ui-avatars.com/api/?name=#{user.name}&background=random"
  end

  def posts_counter(user)
    user.posts_counter || 0
  end
end

app/views/users/index.html.erb
<%= render "shared/header" %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<% @users.each do |user| %>
    <div class="user-container">
      <img src="<%= user.photo %>" alt="user photo">
      <div>
        <h2>Name: <%= user.name %></h2>
        
        <h4>
          <%= link_to "View profile", user_path(user) %>
        </h4>
      </div>
    </div>
<% end %>
<%= render "shared/footer" %>

app/views/users/show.html.erb
<%= render "shared/header" %>
<div class="show-user-container">

  <div class="show-header">
     <img src="<%= current_user.photo %>" alt="user photo">
        <div>
            <h2>Name: <%= @user.name %></h2>
         <h4>Number of posts: <%= current_user.posts_counter %></h4>
        </div>
  </div>
  <div class="bio">
      <h2>Bio</h2>
      <p><%= current_user.bio %></p>
  </div>
  
  <% @posts.each do |post| %>
        <div class="show-posts">
            <h2><%= post.title %></h2>
            <p><%= post.text %></p>
            <div>
              <span>Comments: <%= post.comments_counter %></span>
              <span>Likes: <%= post.likes_counter %></span>
            </div> 
        </div>   
  <% end %>

</div>

<button type="button">
   <%= link_to "See all posts", user_posts_path(@user.id) %>
</button>

<%= render "shared/footer" %>