config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users, controllers: { confirmations: 'confirmations' }
  # a route that maps the URL "/users/:author_id/posts"
  # to the "index" action of the "posts" controller.
   # It a Nested route to access posts for a specific user
  get "/users/:author_id/posts", to: "posts#index", as: :user_posts
 # a route that maps the URL "/posts/:id" to the "show"
 # action of the "posts" controller.
  get "/posts/:id", to: "posts#show", as: :user_post
  # a route that maps the URL "/users" to the "index" action
  # of the "users" controller. This means that when a user
  # visits the "/users" URL, the "index" action in the
  #"users" controller will be executed.
  root "users#index"
  # a route that maps the URL "/users/:id" to the "show"
  # action of the "users" controller.
  get "/users/:id", to: "users#show", as: :user

  # a route that maps the URL "/posts" to the "create" action of the "posts"
  # controller. This means that when a user submits a POST request to the "/posts"
  # URL, the "create" action in the "posts" controller will be executed.
  post "/posts", to: "posts#create"

 # a route that maps the URL "/posts/:id/comments" to the "create_comment"
 # action of the "posts" controller.
  post "/posts/:id/comments", to: "comments#create_comment", as: :post_comments

 # a route that maps the URL "/posts/:id/likes" to the "create_like"
 # action of the "posts" controller.
  post "/posts/:id/likes", to: "likes#create_like", as: :post_likes

  # route that maps the URL "/users/:author_id/posts" to the "create" action of the "posts"
  # controller.
  post "/users/:author_id/posts", to: "posts#create", as: :create_user_post
  delete "/posts/:id", to: "posts#destroy", as: :delete_post
  delete "/comments/:id", to: "comments#destroy", as: :delete_comment

  namespace :api do
    resources :users, only: [] do
       resources :posts, only: [:index] do
        resources :comments, only: [:index, :create]
      end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, foreign_key: 'author_id'
  # The dependent: :destroy ensures that when a post is deleted, its
  # associated likes and comments will also be deleted.
  has_many :comments, foreign_key: 'post_id', dependent: :destroy
  has_many :likes, foreign_key: 'post_id', dependent: :destroy

  # The line `validates :Title, presence: true, length: {maximum: 250}` is a
  # validation rule for the `Title` attribute of the `Post` model.
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # The function updates the PostCounter attribute of a user by counting
  # the number of posts they have. If there are no posts, it sets the counter to 0.
  def update_posts_count
    user.increment!(:posts_counter)
  end

  def decrement_posts_count
    user.decrement!(:posts_counter)
  end

  # The function returns the five most recent comments in descending order
  # of their creation time.
  def five_most_recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end
# Code to verify if the update_post_comments_counter method is working
# post = Post.first
# post.update_posts_counter
# post.five_most_recent_comments

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @posts = Post.all
    render json: @posts
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # The index function retrieves a user and their posts, and initializes a new post object.
  load_and_authorize_resource

  def index
    @user = current_user
    @posts = @user.posts.includes(:comments)
    @post = Post.new
  end

  # The function assigns variables for a post, comment, like, and user in order
  # to display them in a view.
  def show
    @user = current_user
    @post = Post.find_by(id: params[:id])
    @comment = Comment.new
    @like = Like.new
    cookies[:post_id] = @post.id if @post.present?
    nil unless @post.nil?
  end

  # The `create` function creates a new post and associates it with the current user,
  # then redirects to the user's posts page if successful, or renders the index page
  # with the user's posts if there are errors.
  def create
    @user = current_user
    @post = Post.new(post_params.merge(author_id: @user.id))
    if @post.save

      @post.update_posts_count

      redirect_to user_posts_path(@user), notice: 'Post created successfully.'
    else
      @posts = @user.posts
      render :index
    end
  end

  def destroy
    current_user = User.find(params[:author_id])
    @post = Post.find(params[:id])
    authorize! :destroy, @post
    @post.destroy
    @post.decrement_posts_count
    redirect_to user_posts_path(current_user), notice: 'Post deleted successfully.'
  end

  private

  # The function `post_params` is used to extract and permit specific parameters from
  # the `params` object in a Ruby on Rails application.
  def post_params
    params.require(:post).permit(:title, :text, :author_id, :comments_counter, :likes_counter)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def truncate_text(text)
    "#{text[0..25]}..."
  end
end

app/views/posts/_post.html.erb
<%=  link_to user_post_path(current_user.id, post.id), {class: " d-flex flex-column mt-5 text-decoration-none text-dark"} do%>
     <h2>Post #<%= post.id %></h2>
      <h2><%= post.title %></h2>
     <p><%= truncate_text(post.text) %></p>
     <div class="d-flex likes-comments-container">
       <span>Comments: <%= post.comments_counter || 0 %></span>
       <span>Likes: <%= post.likes_counter || 0 %></span>
     </div>
<%end%>

app/views/posts/index.html.erb
<%= render "shared/header" %>
<div class="posts-container">
  <% @posts.each do |post| %>
    <div class="all-posts-container">
      <div class="all-posts">
         <%= render partial: "posts/post", locals: {post: post, user: @user} %>
                   <% if can?(:destroy, post) %>
            <%= button_to "Delete", delete_post_path(author_id: post.user.id, id: post.id), method: :delete, data: { confirm: "Are you sure?", turbo_confirm: "Are you sure you want to delete this post" } %>
          <% end %>
        </div>
      </div>
    </div>

    <h1 class="comments-header">comments</h1>
    <div class="post-comments">
    
      <% post.comments.each do |comment| %>
              <h4>Username: <%= comment.user.name %> - <span> <%= comment.text %> </span>
       
     </h4>
      <% end %>
    </div>
  <% end %>
</div>

<%= form_with(model: @post, url: create_user_post_path(current_user), method: :post) do |form| %>
  <%= form.hidden_field :author_id, value: current_user.id %>
  <%= form.hidden_field :comments_counter, value: 0 %>
  <%= form.hidden_field :likes_counter, value: 0 %>
  <h2>Create a new post</h2>
  <%= form.label :title %>
  <%= form.text_field :title %><br>

  <%= form.label :text %>
  <%= form.text_area :text %><br>

  <%= form.submit "Create Post" %><br>
<% end %>

<button type="button">Pagination</button>

<%= render "shared/footer" %>

app/views/posts/show.html.erb
<%= render "shared/header" %>
  <div class="single-post">
    <h2><%= @post.title %></h2>
    <div>
      <span>Comments: <%= @post.comments_counter %></span>
      <span>Likes: <%= @post.likes_counter %></span>
    </div>
    <p><%= @post.text %></p>
    <%= form_with(model: @like, url: post_likes_path(@post), method: :post) do |form| %>
    <%= form.hidden_field :users_id, value: @user.id %>
    <%= form.hidden_field :posts_id, value: @post.id %>
    <%= form.submit "Like" %>
  <% end %>
 </div>

  <%= form_with(model: @comment, url: post_comments_path(@post), method: :post) do |form| %>
    <h2>Add a comment</h2>
    <%= form.label :text %>
    <%= form.text_area :text %><br>

    <%= form.submit "Add Comment" %><br>
  <% end %>
 </div>

 <h1 class="comments-header"> comments</h1>
  <div class="post-comments">
  <% @post.comments.each do |comment| %>
   <h4>Username: <%= comment.user.name %> - <span> <%= comment.text %> </span>
       <% if can?(:destroy, comment) %>
          <%= button_to "Delete", delete_comment_path(author_id: @post.user.id, posts_id: @post.id, id: comment.id), method: :delete, data: { confirm: "Are you sure?", turbo_confirm: "Are you sure you want to delete this comment" } %>
        <% end %>
     </h4>
  <% end %>
  </div>
  <button type="button">
<%=  link_to "Go back", root_path, class: "btn btn-primary w-25"%>
</button>
<%= render "shared/footer" %>